# The name of the mod loader type to load - for regular FML @Mod mods it should be javafml
modLoader="javafml"
# A version range to match for said mod loader - for regular FML @Mod it will be the forge version
# Forge for 1.14.4 is version 28
loaderVersion="[31,)"
# A URL to refer people to when problems occur with this mod
issueTrackerURL="https://github.com/deletey/compact-storage/issues"
# If the mods defined in this file should show as seperate resource packs
showAsResourcePack=false

[[mods]]
  modId="compact-storage"
  version="4.0.0"
  displayName="Compact Storage"
  updateJSONURL="https://minecraftforge.net/versions.json"
  displayURL="minecraftforge.net"
  logoFile="assets/examplemod/textures/logo.png"
  credits="deletey"
  authors="deletey"
  description='''
  24x12 chests and backpacks!
  '''

  [[dependencies.compact-storage]]
    modId="forge"
    mandatory=true
    versionRange="[31,)"
    ordering="NONE"
    side="BOTH"